Portfolio project
gracekabaghe/portfolio pull request #1
Opened 2021-09-17 12:31 UTC by gracekabaghe

This is my portfolio showing both my soft and technical skill-sets.

2021-09-17 13:55 UTC, Mihndim2020 requested changes
### Hi @gracekabaghe, 

### Good job so far!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file
:heavy_check_mark: Linters are passing
:heavy_check_mark: The project is running

There are some issues that you still need to work on to get this project approved, but you are almost there!
![ALMOST-MINION](https://user-images.githubusercontent.com/65852621/133680327-431cb21d-ad7c-483a-84eb-21b733980a04.png)



# Status: Require Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please also consider:
- [OPTIONAL] using imperative tense in your commit messages

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-17 13:55 UTC, Mihndim2020 commented on index.html
> +        </div>
- [ ] The container of this section should be a `<header>` tag. Please kindly fix that as it is part of the project requirements. This also makes your html more semantic, which is good for assistive technologies, and search engine optimization. Please checkout this [link](https://www.w3schools.com/html/html5_semantic_elements.asp) about semantic html.
- [ ] Please also make sure you insert the proper background images as in the design. 
- [ ] Please make sure this section has the margins (top, bottom, left, right) defined in the design
- [ ] Please use the fonts and colors (background and font) defined for the template

     ## Your implementation ##    
![grace](https://user-images.githubusercontent.com/65852621/133791003-e778ff60-856a-45d2-b781-1359a644ee0e.png)

 ## The design ##     
![thedesign](https://user-images.githubusercontent.com/65852621/133791111-63bf54b4-4238-48f4-9277-d2ef5f20da87.png)

2021-09-17 13:55 UTC, Mihndim2020 commented on index.html
> +                G
- [ ] The logo should be link tag. Please kindly fix that. If you check on most websites, you will notice that the logo is a link the takes you to the home page, enhancing the site navigation.

2021-09-17 13:55 UTC, Mihndim2020 commented on index.html
> +            </div>
- [ ] The hamburger button should be within a `<nav>` tag, as this is part of the project requirements. Please fix that.

2021-09-17 13:55 UTC, Mihndim2020 commented on index.html
> +        <div class="section">
- [ ] The container of this section should be a `<section>` tag as per requirements and for semantic purposes as explained above. Please kindly fix that.

2021-09-17 13:55 UTC, Mihndim2020 commented on index.html
> +                <p>Hey! <br>
- [ ] The main title is an `<h1>` tag. Please kindly fix that. 
- [ ] The content should be aligned with flexbox.
- [ ] The section should have margins (top, bottom, left, right) defined in the design.
- [ ] The section should use the font and colors (background and font) defined for the template. Please kindly fix that.

2021-09-17 13:55 UTC, Mihndim2020 commented on index.html
> +            </div>
- [ ] The list of icons uses a `<ul>` tag to group them, and `<li>` per icon; each icon has a link (`<a>` tag). Please kindly fix that.

2021-09-18 12:34 UTC, Leon-Mbegera approved these changes
Hi @gracekabaghe , 

# Approved 🎉 

- Well done on implementing all the requested changes by the previous reviewer 👍 

Your project is complete!  There is nothing else to say other than... it's time to merge it and proceed onto the next stage. :shipit: 
Congratulations! 🎉 

## Optional 
- [ ] Beware this is not a required change but a suggestion. The previous reviewer missed to point out that your social media icons need some margins in between each other as per the given design. It would be nice to fix that. However, your project is still approved 😄 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-18 15:31 UTC, merged